//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyAll.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyAll.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Card.
        /// </summary>
        internal static string AddCardTitle {
            get {
                return ResourceManager.GetString("AddCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add from gallery.
        /// </summary>
        internal static string AddFromGallery {
            get {
                return ResourceManager.GetString("AddFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new card.
        /// </summary>
        internal static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card name.
        /// </summary>
        internal static string CardNamePlaceholder {
            get {
                return ResourceManager.GetString("CardNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose import method.
        /// </summary>
        internal static string ChooseImportMethod {
            get {
                return ResourceManager.GetString("ChooseImportMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string CopiedToClipboardMessage {
            get {
                return ResourceManager.GetString("CopiedToClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode message. Make sure you&apos;re importing code generated by this app!.
        /// </summary>
        internal static string DecodeErrorMessage {
            get {
                return ResourceManager.GetString("DecodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode code:.
        /// </summary>
        internal static string DecodeErrorPrefix {
            get {
                return ResourceManager.GetString("DecodeErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete card {0}?.
        /// </summary>
        internal static string DeleteCardMessage {
            get {
                return ResourceManager.GetString("DeleteCardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete card.
        /// </summary>
        internal static string DeleteCardTitle {
            get {
                return ResourceManager.GetString("DeleteCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all data?.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data.
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter card name.
        /// </summary>
        internal static string EnterCardNameError {
            get {
                return ResourceManager.GetString("EnterCardNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name and scan code.
        /// </summary>
        internal static string EnterNameAndScanError {
            get {
                return ResourceManager.GetString("EnterNameAndScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text....
        /// </summary>
        internal static string EnterTextPlaceholder {
            get {
                return ResourceManager.GetString("EnterTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from another device.
        /// </summary>
        internal static string ImportFromDevice {
            get {
                return ResourceManager.GetString("ImportFromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from image.
        /// </summary>
        internal static string ImportFromImage {
            get {
                return ResourceManager.GetString("ImportFromImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from text.
        /// </summary>
        internal static string ImportFromText {
            get {
                return ResourceManager.GetString("ImportFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends.
        /// </summary>
        internal static string InviteFriends {
            get {
                return ResourceManager.GetString("InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, check out this loyalty app! https://play.google.com/store/apps/details?id=com.companyname.loyall.
        /// </summary>
        internal static string InviteFriendsText {
            get {
                return ResourceManager.GetString("InviteFriendsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load cards.
        /// </summary>
        internal static string LoadCardsError {
            get {
                return ResourceManager.GetString("LoadCardsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No QR/barcode found on the image..
        /// </summary>
        internal static string NoBarcodeFound {
            get {
                return ResourceManager.GetString("NoBarcodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any cards to share.
        /// </summary>
        internal static string NoCardsMessage {
            get {
                return ResourceManager.GetString("NoCardsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards.
        /// </summary>
        internal static string NoCardsTitle {
            get {
                return ResourceManager.GetString("NoCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste encoded message.
        /// </summary>
        internal static string PasteEncodedMessage {
            get {
                return ResourceManager.GetString("PasteEncodedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and security.
        /// </summary>
        internal static string PrivacyAndSecurity {
            get {
                return ResourceManager.GetString("PrivacyAndSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code too big? Tap to copy this text!.
        /// </summary>
        internal static string QrCodeTooBigMessage {
            get {
                return ResourceManager.GetString("QrCodeTooBigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate us.
        /// </summary>
        internal static string RateUs {
            get {
                return ResourceManager.GetString("RateUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan code.
        /// </summary>
        internal static string ScanCode {
            get {
                return ResourceManager.GetString("ScanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search cards....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAllCards {
            get {
                return ResourceManager.GetString("SelectAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareButton {
            get {
                return ResourceManager.GetString("ShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can share your loyalty cards. Generate QR code or copy the code and then import on another device to share the same cards!.
        /// </summary>
        internal static string ShareCardHelpMessage {
            get {
                return ResourceManager.GetString("ShareCardHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cards to share.
        /// </summary>
        internal static string ShareCardsTitle {
            get {
                return ResourceManager.GetString("ShareCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Card.
        /// </summary>
        internal static string ShareCardTitle {
            get {
                return ResourceManager.GetString("ShareCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show GDPR consent again.
        /// </summary>
        internal static string ShowGDPRConsent {
            get {
                return ResourceManager.GetString("ShowGDPRConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to copy sharing link....
        /// </summary>
        internal static string TapToCopyMessage {
            get {
                return ResourceManager.GetString("TapToCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cards.
        /// </summary>
        internal static string TitleCards {
            get {
                return ResourceManager.GetString("TitleCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported code.
        /// </summary>
        internal static string UnsupportedCode {
            get {
                return ResourceManager.GetString("UnsupportedCode", resourceCulture);
            }
        }
    }
}
